[package]
name = "minecraft-sys"
version = "0.1.0"
edition = "2021"

[features]
default = ["sync"]
async = ["tokio/full"]
sync = ["reqwest/blocking"]

[dependencies]
reqwest = "0.12.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.0"